services:
  router-playground:
    depends_on:
      collector:
        condition: service_healthy
  collector:
    depends_on:
      postgres:
        condition: service_healthy
      collector-migrate:
        condition: service_completed_successfully
