services:
  playground-next:
    depends_on:
      collector:
        condition: service_healthy
  playground-react:
    depends_on:
      collector:
        condition: service_healthy
  playground-tanstack:
    depends_on:
      collector:
        condition: service_healthy
  collector:
    depends_on:
      postgres:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
